import { CreateUserData, CreateUserVariables, CreateChatroomData, CreateChatroomVariables, JoinChatroomData, JoinChatroomVariables, LeaveChatroomData, LeaveChatroomVariables, SendMessageData, SendMessageVariables, UpdateStatusData, UpdateStatusVariables, UpdateUserImageData, UpdateUserImageVariables, UpsertFriendWithData, UpsertFriendWithVariables, SendFriendWithRequestData, SendFriendWithRequestVariables, AcceptFriendWithRequestData, AcceptFriendWithRequestVariables, AcceptFriendWithRequestBidirectionalData, AcceptFriendWithRequestBidirectionalVariables, RejectFriendWithRequestBidirectionalData, RejectFriendWithRequestBidirectionalVariables, DeleteFriendWithData, DeleteFriendWithVariables, UpdateChatroomDetailsData, UpdateChatroomDetailsVariables, UpsertChatroomStatData, UpsertChatroomStatVariables, UpdateCityNameData, UpdateCityNameVariables, DeleteChatroomStatData, DeleteChatroomStatVariables, UpdateStatValueData, UpdateStatValueVariables, UpsertGlobalStatData, UpsertGlobalStatVariables, OpenChatroomSessionData, OpenChatroomSessionVariables, CloseChatroomSessionData, CloseChatroomSessionVariables, HeartbeatChatroomSessionData, HeartbeatChatroomSessionVariables, RecordChatroomVisitData, RecordChatroomVisitVariables, TrimOldVisitsData, TrimOldVisitsVariables, CreateNotificationData, CreateNotificationVariables, MarkNotificationReadData, MarkNotificationReadVariables, MarkAllNotificationsReadData, MarkAllNotificationsReadVariables, InitializeChatroomStatsDefaultsData, InitializeChatroomStatsDefaultsVariables, IncrementChatroomStatData, IncrementChatroomStatVariables, CreatePlayroomSessionData, CreatePlayroomSessionVariables, UpdatePlayroomSessionDetailsData, UpdatePlayroomSessionDetailsVariables, UpdatePlayroomInvitedUserJoinedAtData, UpdatePlayroomInvitedUserJoinedAtVariables, DeletePlayroomInvitedUserJoinedAtData, DeletePlayroomInvitedUserJoinedAtVariables, UpdatePlayroomCreatorUserHeartbeatData, UpdatePlayroomCreatorUserHeartbeatVariables, DeletePlayroomCreatorUserHeartbeatData, DeletePlayroomCreatorUserHeartbeatVariables, UpdatePlayroomInvitedUserHeartbeatData, UpdatePlayroomInvitedUserHeartbeatVariables, DeletePlayroomInvitedUserHeartbeatData, DeletePlayroomInvitedUserHeartbeatVariables, UpdatePlayroomSpectatorsData, UpdatePlayroomSpectatorsVariables, DeletePlayroomSpectatorsData, DeletePlayroomSpectatorsVariables, UpdatePlayroomSpectatorsJoinedData, UpdatePlayroomSpectatorsJoinedVariables, DeletePlayroomSpectatorsJoinedData, DeletePlayroomSpectatorsJoinedVariables, ClosePlayroomSessionData, ClosePlayroomSessionVariables, DeletePlayroomSessionData, DeletePlayroomSessionVariables, GetUserData, GetUserVariables, ListPublicChatroomsData, ListPublicChatroomsVariables, GetChatroomMessagesData, GetChatroomMessagesVariables, ListChatroomsByOwnerData, ListChatroomsByOwnerVariables, ListChatroomsByCityData, ListChatroomsByCityVariables, SearchCitiesData, SearchCitiesVariables, IsMemberData, IsMemberVariables, GetFriendWithData, GetFriendWithVariables, ListFriendWithByUserData, ListFriendWithByUserVariables, ListPendingFriendRequestsReceivedData, ListPendingFriendRequestsReceivedVariables, ListAcceptedFriendConnectionsData, ListAcceptedFriendConnectionsVariables, ListMyChatroomsData, ListMyChatroomsVariables, GetGlobalStatsData, GetGlobalStatData, GetGlobalStatVariables, ListActiveSessionsByUserData, ListActiveSessionsByUserVariables, ListActiveSessionsGlobalData, ListActiveSessionsGlobalVariables, ListRecentVisitedChatroomsData, ListRecentVisitedChatroomsVariables, ListNotificationsByRecipientData, ListNotificationsByRecipientVariables, CountUnreadNotificationsData, CountUnreadNotificationsVariables, ListChatroomStatsByChatroomIdsData, ListChatroomStatsByChatroomIdsVariables, FetchPlayroomCreatorTokenData, FetchPlayroomCreatorTokenVariables, FetchPlayroomInvitedUserTokenData, FetchPlayroomInvitedUserTokenVariables, FetchPlayroomParticipantTokenData, FetchPlayroomParticipantTokenVariables, FetchPlayroomParticipantUserIdsData, FetchPlayroomParticipantUserIdsVariables, FetchPlayroomInvitedUserJoinedAtData, FetchPlayroomInvitedUserJoinedAtVariables, FetchPlayroomCreatorUserHeartbeatData, FetchPlayroomCreatorUserHeartbeatVariables, FetchPlayroomInvitedUserHeartbeatData, FetchPlayroomInvitedUserHeartbeatVariables, FetchPlayroomSpectatorsData, FetchPlayroomSpectatorsVariables, FetchPlayroomSpectatorsJoinedData, FetchPlayroomSpectatorsJoinedVariables, IsUserInPlayroomSpectatorsData, IsUserInPlayroomSpectatorsVariables, ListActivePlayroomSessionsByUserAndGameData, ListActivePlayroomSessionsByUserAndGameVariables, GetPlayroomSessionByPlayroomSessionIdData, GetPlayroomSessionByPlayroomSessionIdVariables, GetActivePlayroomSessionByPlayroomSessionIdData, GetActivePlayroomSessionByPlayroomSessionIdVariables } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useCreateUser(options?: useDataConnectMutationOptions<CreateUserData, FirebaseError, CreateUserVariables>): UseDataConnectMutationResult<CreateUserData, CreateUserVariables>;
export function useCreateUser(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUserData, FirebaseError, CreateUserVariables>): UseDataConnectMutationResult<CreateUserData, CreateUserVariables>;

export function useCreateChatroom(options?: useDataConnectMutationOptions<CreateChatroomData, FirebaseError, CreateChatroomVariables>): UseDataConnectMutationResult<CreateChatroomData, CreateChatroomVariables>;
export function useCreateChatroom(dc: DataConnect, options?: useDataConnectMutationOptions<CreateChatroomData, FirebaseError, CreateChatroomVariables>): UseDataConnectMutationResult<CreateChatroomData, CreateChatroomVariables>;

export function useJoinChatroom(options?: useDataConnectMutationOptions<JoinChatroomData, FirebaseError, JoinChatroomVariables>): UseDataConnectMutationResult<JoinChatroomData, JoinChatroomVariables>;
export function useJoinChatroom(dc: DataConnect, options?: useDataConnectMutationOptions<JoinChatroomData, FirebaseError, JoinChatroomVariables>): UseDataConnectMutationResult<JoinChatroomData, JoinChatroomVariables>;

export function useLeaveChatroom(options?: useDataConnectMutationOptions<LeaveChatroomData, FirebaseError, LeaveChatroomVariables>): UseDataConnectMutationResult<LeaveChatroomData, LeaveChatroomVariables>;
export function useLeaveChatroom(dc: DataConnect, options?: useDataConnectMutationOptions<LeaveChatroomData, FirebaseError, LeaveChatroomVariables>): UseDataConnectMutationResult<LeaveChatroomData, LeaveChatroomVariables>;

export function useSendMessage(options?: useDataConnectMutationOptions<SendMessageData, FirebaseError, SendMessageVariables>): UseDataConnectMutationResult<SendMessageData, SendMessageVariables>;
export function useSendMessage(dc: DataConnect, options?: useDataConnectMutationOptions<SendMessageData, FirebaseError, SendMessageVariables>): UseDataConnectMutationResult<SendMessageData, SendMessageVariables>;

export function useUpdateStatus(options?: useDataConnectMutationOptions<UpdateStatusData, FirebaseError, UpdateStatusVariables>): UseDataConnectMutationResult<UpdateStatusData, UpdateStatusVariables>;
export function useUpdateStatus(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateStatusData, FirebaseError, UpdateStatusVariables>): UseDataConnectMutationResult<UpdateStatusData, UpdateStatusVariables>;

export function useUpdateUserImage(options?: useDataConnectMutationOptions<UpdateUserImageData, FirebaseError, UpdateUserImageVariables>): UseDataConnectMutationResult<UpdateUserImageData, UpdateUserImageVariables>;
export function useUpdateUserImage(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateUserImageData, FirebaseError, UpdateUserImageVariables>): UseDataConnectMutationResult<UpdateUserImageData, UpdateUserImageVariables>;

export function useUpsertFriendWith(options?: useDataConnectMutationOptions<UpsertFriendWithData, FirebaseError, UpsertFriendWithVariables>): UseDataConnectMutationResult<UpsertFriendWithData, UpsertFriendWithVariables>;
export function useUpsertFriendWith(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertFriendWithData, FirebaseError, UpsertFriendWithVariables>): UseDataConnectMutationResult<UpsertFriendWithData, UpsertFriendWithVariables>;

export function useSendFriendWithRequest(options?: useDataConnectMutationOptions<SendFriendWithRequestData, FirebaseError, SendFriendWithRequestVariables>): UseDataConnectMutationResult<SendFriendWithRequestData, SendFriendWithRequestVariables>;
export function useSendFriendWithRequest(dc: DataConnect, options?: useDataConnectMutationOptions<SendFriendWithRequestData, FirebaseError, SendFriendWithRequestVariables>): UseDataConnectMutationResult<SendFriendWithRequestData, SendFriendWithRequestVariables>;

export function useAcceptFriendWithRequest(options?: useDataConnectMutationOptions<AcceptFriendWithRequestData, FirebaseError, AcceptFriendWithRequestVariables>): UseDataConnectMutationResult<AcceptFriendWithRequestData, AcceptFriendWithRequestVariables>;
export function useAcceptFriendWithRequest(dc: DataConnect, options?: useDataConnectMutationOptions<AcceptFriendWithRequestData, FirebaseError, AcceptFriendWithRequestVariables>): UseDataConnectMutationResult<AcceptFriendWithRequestData, AcceptFriendWithRequestVariables>;

export function useAcceptFriendWithRequestBidirectional(options?: useDataConnectMutationOptions<AcceptFriendWithRequestBidirectionalData, FirebaseError, AcceptFriendWithRequestBidirectionalVariables>): UseDataConnectMutationResult<AcceptFriendWithRequestBidirectionalData, AcceptFriendWithRequestBidirectionalVariables>;
export function useAcceptFriendWithRequestBidirectional(dc: DataConnect, options?: useDataConnectMutationOptions<AcceptFriendWithRequestBidirectionalData, FirebaseError, AcceptFriendWithRequestBidirectionalVariables>): UseDataConnectMutationResult<AcceptFriendWithRequestBidirectionalData, AcceptFriendWithRequestBidirectionalVariables>;

export function useRejectFriendWithRequestBidirectional(options?: useDataConnectMutationOptions<RejectFriendWithRequestBidirectionalData, FirebaseError, RejectFriendWithRequestBidirectionalVariables>): UseDataConnectMutationResult<RejectFriendWithRequestBidirectionalData, RejectFriendWithRequestBidirectionalVariables>;
export function useRejectFriendWithRequestBidirectional(dc: DataConnect, options?: useDataConnectMutationOptions<RejectFriendWithRequestBidirectionalData, FirebaseError, RejectFriendWithRequestBidirectionalVariables>): UseDataConnectMutationResult<RejectFriendWithRequestBidirectionalData, RejectFriendWithRequestBidirectionalVariables>;

export function useDeleteFriendWith(options?: useDataConnectMutationOptions<DeleteFriendWithData, FirebaseError, DeleteFriendWithVariables>): UseDataConnectMutationResult<DeleteFriendWithData, DeleteFriendWithVariables>;
export function useDeleteFriendWith(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteFriendWithData, FirebaseError, DeleteFriendWithVariables>): UseDataConnectMutationResult<DeleteFriendWithData, DeleteFriendWithVariables>;

export function useUpdateChatroomDetails(options?: useDataConnectMutationOptions<UpdateChatroomDetailsData, FirebaseError, UpdateChatroomDetailsVariables>): UseDataConnectMutationResult<UpdateChatroomDetailsData, UpdateChatroomDetailsVariables>;
export function useUpdateChatroomDetails(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateChatroomDetailsData, FirebaseError, UpdateChatroomDetailsVariables>): UseDataConnectMutationResult<UpdateChatroomDetailsData, UpdateChatroomDetailsVariables>;

export function useUpsertChatroomStat(options?: useDataConnectMutationOptions<UpsertChatroomStatData, FirebaseError, UpsertChatroomStatVariables>): UseDataConnectMutationResult<UpsertChatroomStatData, UpsertChatroomStatVariables>;
export function useUpsertChatroomStat(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertChatroomStatData, FirebaseError, UpsertChatroomStatVariables>): UseDataConnectMutationResult<UpsertChatroomStatData, UpsertChatroomStatVariables>;

export function useUpdateCityName(options?: useDataConnectMutationOptions<UpdateCityNameData, FirebaseError, UpdateCityNameVariables>): UseDataConnectMutationResult<UpdateCityNameData, UpdateCityNameVariables>;
export function useUpdateCityName(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateCityNameData, FirebaseError, UpdateCityNameVariables>): UseDataConnectMutationResult<UpdateCityNameData, UpdateCityNameVariables>;

export function useDeleteChatroomStat(options?: useDataConnectMutationOptions<DeleteChatroomStatData, FirebaseError, DeleteChatroomStatVariables>): UseDataConnectMutationResult<DeleteChatroomStatData, DeleteChatroomStatVariables>;
export function useDeleteChatroomStat(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteChatroomStatData, FirebaseError, DeleteChatroomStatVariables>): UseDataConnectMutationResult<DeleteChatroomStatData, DeleteChatroomStatVariables>;

export function useUpdateStatValue(options?: useDataConnectMutationOptions<UpdateStatValueData, FirebaseError, UpdateStatValueVariables>): UseDataConnectMutationResult<UpdateStatValueData, UpdateStatValueVariables>;
export function useUpdateStatValue(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateStatValueData, FirebaseError, UpdateStatValueVariables>): UseDataConnectMutationResult<UpdateStatValueData, UpdateStatValueVariables>;

export function useUpsertGlobalStat(options?: useDataConnectMutationOptions<UpsertGlobalStatData, FirebaseError, UpsertGlobalStatVariables>): UseDataConnectMutationResult<UpsertGlobalStatData, UpsertGlobalStatVariables>;
export function useUpsertGlobalStat(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertGlobalStatData, FirebaseError, UpsertGlobalStatVariables>): UseDataConnectMutationResult<UpsertGlobalStatData, UpsertGlobalStatVariables>;

export function useOpenChatroomSession(options?: useDataConnectMutationOptions<OpenChatroomSessionData, FirebaseError, OpenChatroomSessionVariables>): UseDataConnectMutationResult<OpenChatroomSessionData, OpenChatroomSessionVariables>;
export function useOpenChatroomSession(dc: DataConnect, options?: useDataConnectMutationOptions<OpenChatroomSessionData, FirebaseError, OpenChatroomSessionVariables>): UseDataConnectMutationResult<OpenChatroomSessionData, OpenChatroomSessionVariables>;

export function useCloseChatroomSession(options?: useDataConnectMutationOptions<CloseChatroomSessionData, FirebaseError, CloseChatroomSessionVariables>): UseDataConnectMutationResult<CloseChatroomSessionData, CloseChatroomSessionVariables>;
export function useCloseChatroomSession(dc: DataConnect, options?: useDataConnectMutationOptions<CloseChatroomSessionData, FirebaseError, CloseChatroomSessionVariables>): UseDataConnectMutationResult<CloseChatroomSessionData, CloseChatroomSessionVariables>;

export function useHeartbeatChatroomSession(options?: useDataConnectMutationOptions<HeartbeatChatroomSessionData, FirebaseError, HeartbeatChatroomSessionVariables>): UseDataConnectMutationResult<HeartbeatChatroomSessionData, HeartbeatChatroomSessionVariables>;
export function useHeartbeatChatroomSession(dc: DataConnect, options?: useDataConnectMutationOptions<HeartbeatChatroomSessionData, FirebaseError, HeartbeatChatroomSessionVariables>): UseDataConnectMutationResult<HeartbeatChatroomSessionData, HeartbeatChatroomSessionVariables>;

export function useRecordChatroomVisit(options?: useDataConnectMutationOptions<RecordChatroomVisitData, FirebaseError, RecordChatroomVisitVariables>): UseDataConnectMutationResult<RecordChatroomVisitData, RecordChatroomVisitVariables>;
export function useRecordChatroomVisit(dc: DataConnect, options?: useDataConnectMutationOptions<RecordChatroomVisitData, FirebaseError, RecordChatroomVisitVariables>): UseDataConnectMutationResult<RecordChatroomVisitData, RecordChatroomVisitVariables>;

export function useTrimOldVisits(options?: useDataConnectMutationOptions<TrimOldVisitsData, FirebaseError, TrimOldVisitsVariables>): UseDataConnectMutationResult<TrimOldVisitsData, TrimOldVisitsVariables>;
export function useTrimOldVisits(dc: DataConnect, options?: useDataConnectMutationOptions<TrimOldVisitsData, FirebaseError, TrimOldVisitsVariables>): UseDataConnectMutationResult<TrimOldVisitsData, TrimOldVisitsVariables>;

export function useCreateNotification(options?: useDataConnectMutationOptions<CreateNotificationData, FirebaseError, CreateNotificationVariables>): UseDataConnectMutationResult<CreateNotificationData, CreateNotificationVariables>;
export function useCreateNotification(dc: DataConnect, options?: useDataConnectMutationOptions<CreateNotificationData, FirebaseError, CreateNotificationVariables>): UseDataConnectMutationResult<CreateNotificationData, CreateNotificationVariables>;

export function useMarkNotificationRead(options?: useDataConnectMutationOptions<MarkNotificationReadData, FirebaseError, MarkNotificationReadVariables>): UseDataConnectMutationResult<MarkNotificationReadData, MarkNotificationReadVariables>;
export function useMarkNotificationRead(dc: DataConnect, options?: useDataConnectMutationOptions<MarkNotificationReadData, FirebaseError, MarkNotificationReadVariables>): UseDataConnectMutationResult<MarkNotificationReadData, MarkNotificationReadVariables>;

export function useMarkAllNotificationsRead(options?: useDataConnectMutationOptions<MarkAllNotificationsReadData, FirebaseError, MarkAllNotificationsReadVariables>): UseDataConnectMutationResult<MarkAllNotificationsReadData, MarkAllNotificationsReadVariables>;
export function useMarkAllNotificationsRead(dc: DataConnect, options?: useDataConnectMutationOptions<MarkAllNotificationsReadData, FirebaseError, MarkAllNotificationsReadVariables>): UseDataConnectMutationResult<MarkAllNotificationsReadData, MarkAllNotificationsReadVariables>;

export function useInitializeChatroomStatsDefaults(options?: useDataConnectMutationOptions<InitializeChatroomStatsDefaultsData, FirebaseError, InitializeChatroomStatsDefaultsVariables>): UseDataConnectMutationResult<InitializeChatroomStatsDefaultsData, InitializeChatroomStatsDefaultsVariables>;
export function useInitializeChatroomStatsDefaults(dc: DataConnect, options?: useDataConnectMutationOptions<InitializeChatroomStatsDefaultsData, FirebaseError, InitializeChatroomStatsDefaultsVariables>): UseDataConnectMutationResult<InitializeChatroomStatsDefaultsData, InitializeChatroomStatsDefaultsVariables>;

export function useIncrementChatroomStat(options?: useDataConnectMutationOptions<IncrementChatroomStatData, FirebaseError, IncrementChatroomStatVariables>): UseDataConnectMutationResult<IncrementChatroomStatData, IncrementChatroomStatVariables>;
export function useIncrementChatroomStat(dc: DataConnect, options?: useDataConnectMutationOptions<IncrementChatroomStatData, FirebaseError, IncrementChatroomStatVariables>): UseDataConnectMutationResult<IncrementChatroomStatData, IncrementChatroomStatVariables>;

export function useCreatePlayroomSession(options?: useDataConnectMutationOptions<CreatePlayroomSessionData, FirebaseError, CreatePlayroomSessionVariables>): UseDataConnectMutationResult<CreatePlayroomSessionData, CreatePlayroomSessionVariables>;
export function useCreatePlayroomSession(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePlayroomSessionData, FirebaseError, CreatePlayroomSessionVariables>): UseDataConnectMutationResult<CreatePlayroomSessionData, CreatePlayroomSessionVariables>;

export function useUpdatePlayroomSessionDetails(options?: useDataConnectMutationOptions<UpdatePlayroomSessionDetailsData, FirebaseError, UpdatePlayroomSessionDetailsVariables>): UseDataConnectMutationResult<UpdatePlayroomSessionDetailsData, UpdatePlayroomSessionDetailsVariables>;
export function useUpdatePlayroomSessionDetails(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlayroomSessionDetailsData, FirebaseError, UpdatePlayroomSessionDetailsVariables>): UseDataConnectMutationResult<UpdatePlayroomSessionDetailsData, UpdatePlayroomSessionDetailsVariables>;

export function useUpdatePlayroomInvitedUserJoinedAt(options?: useDataConnectMutationOptions<UpdatePlayroomInvitedUserJoinedAtData, FirebaseError, UpdatePlayroomInvitedUserJoinedAtVariables>): UseDataConnectMutationResult<UpdatePlayroomInvitedUserJoinedAtData, UpdatePlayroomInvitedUserJoinedAtVariables>;
export function useUpdatePlayroomInvitedUserJoinedAt(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlayroomInvitedUserJoinedAtData, FirebaseError, UpdatePlayroomInvitedUserJoinedAtVariables>): UseDataConnectMutationResult<UpdatePlayroomInvitedUserJoinedAtData, UpdatePlayroomInvitedUserJoinedAtVariables>;

export function useDeletePlayroomInvitedUserJoinedAt(options?: useDataConnectMutationOptions<DeletePlayroomInvitedUserJoinedAtData, FirebaseError, DeletePlayroomInvitedUserJoinedAtVariables>): UseDataConnectMutationResult<DeletePlayroomInvitedUserJoinedAtData, DeletePlayroomInvitedUserJoinedAtVariables>;
export function useDeletePlayroomInvitedUserJoinedAt(dc: DataConnect, options?: useDataConnectMutationOptions<DeletePlayroomInvitedUserJoinedAtData, FirebaseError, DeletePlayroomInvitedUserJoinedAtVariables>): UseDataConnectMutationResult<DeletePlayroomInvitedUserJoinedAtData, DeletePlayroomInvitedUserJoinedAtVariables>;

export function useUpdatePlayroomCreatorUserHeartbeat(options?: useDataConnectMutationOptions<UpdatePlayroomCreatorUserHeartbeatData, FirebaseError, UpdatePlayroomCreatorUserHeartbeatVariables>): UseDataConnectMutationResult<UpdatePlayroomCreatorUserHeartbeatData, UpdatePlayroomCreatorUserHeartbeatVariables>;
export function useUpdatePlayroomCreatorUserHeartbeat(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlayroomCreatorUserHeartbeatData, FirebaseError, UpdatePlayroomCreatorUserHeartbeatVariables>): UseDataConnectMutationResult<UpdatePlayroomCreatorUserHeartbeatData, UpdatePlayroomCreatorUserHeartbeatVariables>;

export function useDeletePlayroomCreatorUserHeartbeat(options?: useDataConnectMutationOptions<DeletePlayroomCreatorUserHeartbeatData, FirebaseError, DeletePlayroomCreatorUserHeartbeatVariables>): UseDataConnectMutationResult<DeletePlayroomCreatorUserHeartbeatData, DeletePlayroomCreatorUserHeartbeatVariables>;
export function useDeletePlayroomCreatorUserHeartbeat(dc: DataConnect, options?: useDataConnectMutationOptions<DeletePlayroomCreatorUserHeartbeatData, FirebaseError, DeletePlayroomCreatorUserHeartbeatVariables>): UseDataConnectMutationResult<DeletePlayroomCreatorUserHeartbeatData, DeletePlayroomCreatorUserHeartbeatVariables>;

export function useUpdatePlayroomInvitedUserHeartbeat(options?: useDataConnectMutationOptions<UpdatePlayroomInvitedUserHeartbeatData, FirebaseError, UpdatePlayroomInvitedUserHeartbeatVariables>): UseDataConnectMutationResult<UpdatePlayroomInvitedUserHeartbeatData, UpdatePlayroomInvitedUserHeartbeatVariables>;
export function useUpdatePlayroomInvitedUserHeartbeat(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlayroomInvitedUserHeartbeatData, FirebaseError, UpdatePlayroomInvitedUserHeartbeatVariables>): UseDataConnectMutationResult<UpdatePlayroomInvitedUserHeartbeatData, UpdatePlayroomInvitedUserHeartbeatVariables>;

export function useDeletePlayroomInvitedUserHeartbeat(options?: useDataConnectMutationOptions<DeletePlayroomInvitedUserHeartbeatData, FirebaseError, DeletePlayroomInvitedUserHeartbeatVariables>): UseDataConnectMutationResult<DeletePlayroomInvitedUserHeartbeatData, DeletePlayroomInvitedUserHeartbeatVariables>;
export function useDeletePlayroomInvitedUserHeartbeat(dc: DataConnect, options?: useDataConnectMutationOptions<DeletePlayroomInvitedUserHeartbeatData, FirebaseError, DeletePlayroomInvitedUserHeartbeatVariables>): UseDataConnectMutationResult<DeletePlayroomInvitedUserHeartbeatData, DeletePlayroomInvitedUserHeartbeatVariables>;

export function useUpdatePlayroomSpectators(options?: useDataConnectMutationOptions<UpdatePlayroomSpectatorsData, FirebaseError, UpdatePlayroomSpectatorsVariables>): UseDataConnectMutationResult<UpdatePlayroomSpectatorsData, UpdatePlayroomSpectatorsVariables>;
export function useUpdatePlayroomSpectators(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlayroomSpectatorsData, FirebaseError, UpdatePlayroomSpectatorsVariables>): UseDataConnectMutationResult<UpdatePlayroomSpectatorsData, UpdatePlayroomSpectatorsVariables>;

export function useDeletePlayroomSpectators(options?: useDataConnectMutationOptions<DeletePlayroomSpectatorsData, FirebaseError, DeletePlayroomSpectatorsVariables>): UseDataConnectMutationResult<DeletePlayroomSpectatorsData, DeletePlayroomSpectatorsVariables>;
export function useDeletePlayroomSpectators(dc: DataConnect, options?: useDataConnectMutationOptions<DeletePlayroomSpectatorsData, FirebaseError, DeletePlayroomSpectatorsVariables>): UseDataConnectMutationResult<DeletePlayroomSpectatorsData, DeletePlayroomSpectatorsVariables>;

export function useUpdatePlayroomSpectatorsJoined(options?: useDataConnectMutationOptions<UpdatePlayroomSpectatorsJoinedData, FirebaseError, UpdatePlayroomSpectatorsJoinedVariables>): UseDataConnectMutationResult<UpdatePlayroomSpectatorsJoinedData, UpdatePlayroomSpectatorsJoinedVariables>;
export function useUpdatePlayroomSpectatorsJoined(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlayroomSpectatorsJoinedData, FirebaseError, UpdatePlayroomSpectatorsJoinedVariables>): UseDataConnectMutationResult<UpdatePlayroomSpectatorsJoinedData, UpdatePlayroomSpectatorsJoinedVariables>;

export function useDeletePlayroomSpectatorsJoined(options?: useDataConnectMutationOptions<DeletePlayroomSpectatorsJoinedData, FirebaseError, DeletePlayroomSpectatorsJoinedVariables>): UseDataConnectMutationResult<DeletePlayroomSpectatorsJoinedData, DeletePlayroomSpectatorsJoinedVariables>;
export function useDeletePlayroomSpectatorsJoined(dc: DataConnect, options?: useDataConnectMutationOptions<DeletePlayroomSpectatorsJoinedData, FirebaseError, DeletePlayroomSpectatorsJoinedVariables>): UseDataConnectMutationResult<DeletePlayroomSpectatorsJoinedData, DeletePlayroomSpectatorsJoinedVariables>;

export function useClosePlayroomSession(options?: useDataConnectMutationOptions<ClosePlayroomSessionData, FirebaseError, ClosePlayroomSessionVariables>): UseDataConnectMutationResult<ClosePlayroomSessionData, ClosePlayroomSessionVariables>;
export function useClosePlayroomSession(dc: DataConnect, options?: useDataConnectMutationOptions<ClosePlayroomSessionData, FirebaseError, ClosePlayroomSessionVariables>): UseDataConnectMutationResult<ClosePlayroomSessionData, ClosePlayroomSessionVariables>;

export function useDeletePlayroomSession(options?: useDataConnectMutationOptions<DeletePlayroomSessionData, FirebaseError, DeletePlayroomSessionVariables>): UseDataConnectMutationResult<DeletePlayroomSessionData, DeletePlayroomSessionVariables>;
export function useDeletePlayroomSession(dc: DataConnect, options?: useDataConnectMutationOptions<DeletePlayroomSessionData, FirebaseError, DeletePlayroomSessionVariables>): UseDataConnectMutationResult<DeletePlayroomSessionData, DeletePlayroomSessionVariables>;

export function useGetUser(vars: GetUserVariables, options?: useDataConnectQueryOptions<GetUserData>): UseDataConnectQueryResult<GetUserData, GetUserVariables>;
export function useGetUser(dc: DataConnect, vars: GetUserVariables, options?: useDataConnectQueryOptions<GetUserData>): UseDataConnectQueryResult<GetUserData, GetUserVariables>;

export function useListPublicChatrooms(vars?: ListPublicChatroomsVariables, options?: useDataConnectQueryOptions<ListPublicChatroomsData>): UseDataConnectQueryResult<ListPublicChatroomsData, ListPublicChatroomsVariables>;
export function useListPublicChatrooms(dc: DataConnect, vars?: ListPublicChatroomsVariables, options?: useDataConnectQueryOptions<ListPublicChatroomsData>): UseDataConnectQueryResult<ListPublicChatroomsData, ListPublicChatroomsVariables>;

export function useGetChatroomMessages(vars: GetChatroomMessagesVariables, options?: useDataConnectQueryOptions<GetChatroomMessagesData>): UseDataConnectQueryResult<GetChatroomMessagesData, GetChatroomMessagesVariables>;
export function useGetChatroomMessages(dc: DataConnect, vars: GetChatroomMessagesVariables, options?: useDataConnectQueryOptions<GetChatroomMessagesData>): UseDataConnectQueryResult<GetChatroomMessagesData, GetChatroomMessagesVariables>;

export function useListChatroomsByOwner(vars: ListChatroomsByOwnerVariables, options?: useDataConnectQueryOptions<ListChatroomsByOwnerData>): UseDataConnectQueryResult<ListChatroomsByOwnerData, ListChatroomsByOwnerVariables>;
export function useListChatroomsByOwner(dc: DataConnect, vars: ListChatroomsByOwnerVariables, options?: useDataConnectQueryOptions<ListChatroomsByOwnerData>): UseDataConnectQueryResult<ListChatroomsByOwnerData, ListChatroomsByOwnerVariables>;

export function useListChatroomsByCity(vars: ListChatroomsByCityVariables, options?: useDataConnectQueryOptions<ListChatroomsByCityData>): UseDataConnectQueryResult<ListChatroomsByCityData, ListChatroomsByCityVariables>;
export function useListChatroomsByCity(dc: DataConnect, vars: ListChatroomsByCityVariables, options?: useDataConnectQueryOptions<ListChatroomsByCityData>): UseDataConnectQueryResult<ListChatroomsByCityData, ListChatroomsByCityVariables>;

export function useSearchCities(vars: SearchCitiesVariables, options?: useDataConnectQueryOptions<SearchCitiesData>): UseDataConnectQueryResult<SearchCitiesData, SearchCitiesVariables>;
export function useSearchCities(dc: DataConnect, vars: SearchCitiesVariables, options?: useDataConnectQueryOptions<SearchCitiesData>): UseDataConnectQueryResult<SearchCitiesData, SearchCitiesVariables>;

export function useIsMember(vars: IsMemberVariables, options?: useDataConnectQueryOptions<IsMemberData>): UseDataConnectQueryResult<IsMemberData, IsMemberVariables>;
export function useIsMember(dc: DataConnect, vars: IsMemberVariables, options?: useDataConnectQueryOptions<IsMemberData>): UseDataConnectQueryResult<IsMemberData, IsMemberVariables>;

export function useGetFriendWith(vars: GetFriendWithVariables, options?: useDataConnectQueryOptions<GetFriendWithData>): UseDataConnectQueryResult<GetFriendWithData, GetFriendWithVariables>;
export function useGetFriendWith(dc: DataConnect, vars: GetFriendWithVariables, options?: useDataConnectQueryOptions<GetFriendWithData>): UseDataConnectQueryResult<GetFriendWithData, GetFriendWithVariables>;

export function useListFriendWithByUser(vars: ListFriendWithByUserVariables, options?: useDataConnectQueryOptions<ListFriendWithByUserData>): UseDataConnectQueryResult<ListFriendWithByUserData, ListFriendWithByUserVariables>;
export function useListFriendWithByUser(dc: DataConnect, vars: ListFriendWithByUserVariables, options?: useDataConnectQueryOptions<ListFriendWithByUserData>): UseDataConnectQueryResult<ListFriendWithByUserData, ListFriendWithByUserVariables>;

export function useListPendingFriendRequestsReceived(vars: ListPendingFriendRequestsReceivedVariables, options?: useDataConnectQueryOptions<ListPendingFriendRequestsReceivedData>): UseDataConnectQueryResult<ListPendingFriendRequestsReceivedData, ListPendingFriendRequestsReceivedVariables>;
export function useListPendingFriendRequestsReceived(dc: DataConnect, vars: ListPendingFriendRequestsReceivedVariables, options?: useDataConnectQueryOptions<ListPendingFriendRequestsReceivedData>): UseDataConnectQueryResult<ListPendingFriendRequestsReceivedData, ListPendingFriendRequestsReceivedVariables>;

export function useListAcceptedFriendConnections(vars: ListAcceptedFriendConnectionsVariables, options?: useDataConnectQueryOptions<ListAcceptedFriendConnectionsData>): UseDataConnectQueryResult<ListAcceptedFriendConnectionsData, ListAcceptedFriendConnectionsVariables>;
export function useListAcceptedFriendConnections(dc: DataConnect, vars: ListAcceptedFriendConnectionsVariables, options?: useDataConnectQueryOptions<ListAcceptedFriendConnectionsData>): UseDataConnectQueryResult<ListAcceptedFriendConnectionsData, ListAcceptedFriendConnectionsVariables>;

export function useListMyChatrooms(vars: ListMyChatroomsVariables, options?: useDataConnectQueryOptions<ListMyChatroomsData>): UseDataConnectQueryResult<ListMyChatroomsData, ListMyChatroomsVariables>;
export function useListMyChatrooms(dc: DataConnect, vars: ListMyChatroomsVariables, options?: useDataConnectQueryOptions<ListMyChatroomsData>): UseDataConnectQueryResult<ListMyChatroomsData, ListMyChatroomsVariables>;

export function useGetGlobalStats(options?: useDataConnectQueryOptions<GetGlobalStatsData>): UseDataConnectQueryResult<GetGlobalStatsData, undefined>;
export function useGetGlobalStats(dc: DataConnect, options?: useDataConnectQueryOptions<GetGlobalStatsData>): UseDataConnectQueryResult<GetGlobalStatsData, undefined>;

export function useGetGlobalStat(vars: GetGlobalStatVariables, options?: useDataConnectQueryOptions<GetGlobalStatData>): UseDataConnectQueryResult<GetGlobalStatData, GetGlobalStatVariables>;
export function useGetGlobalStat(dc: DataConnect, vars: GetGlobalStatVariables, options?: useDataConnectQueryOptions<GetGlobalStatData>): UseDataConnectQueryResult<GetGlobalStatData, GetGlobalStatVariables>;

export function useListActiveSessionsByUser(vars: ListActiveSessionsByUserVariables, options?: useDataConnectQueryOptions<ListActiveSessionsByUserData>): UseDataConnectQueryResult<ListActiveSessionsByUserData, ListActiveSessionsByUserVariables>;
export function useListActiveSessionsByUser(dc: DataConnect, vars: ListActiveSessionsByUserVariables, options?: useDataConnectQueryOptions<ListActiveSessionsByUserData>): UseDataConnectQueryResult<ListActiveSessionsByUserData, ListActiveSessionsByUserVariables>;

export function useListActiveSessionsGlobal(vars?: ListActiveSessionsGlobalVariables, options?: useDataConnectQueryOptions<ListActiveSessionsGlobalData>): UseDataConnectQueryResult<ListActiveSessionsGlobalData, ListActiveSessionsGlobalVariables>;
export function useListActiveSessionsGlobal(dc: DataConnect, vars?: ListActiveSessionsGlobalVariables, options?: useDataConnectQueryOptions<ListActiveSessionsGlobalData>): UseDataConnectQueryResult<ListActiveSessionsGlobalData, ListActiveSessionsGlobalVariables>;

export function useListRecentVisitedChatrooms(vars: ListRecentVisitedChatroomsVariables, options?: useDataConnectQueryOptions<ListRecentVisitedChatroomsData>): UseDataConnectQueryResult<ListRecentVisitedChatroomsData, ListRecentVisitedChatroomsVariables>;
export function useListRecentVisitedChatrooms(dc: DataConnect, vars: ListRecentVisitedChatroomsVariables, options?: useDataConnectQueryOptions<ListRecentVisitedChatroomsData>): UseDataConnectQueryResult<ListRecentVisitedChatroomsData, ListRecentVisitedChatroomsVariables>;

export function useListNotificationsByRecipient(vars: ListNotificationsByRecipientVariables, options?: useDataConnectQueryOptions<ListNotificationsByRecipientData>): UseDataConnectQueryResult<ListNotificationsByRecipientData, ListNotificationsByRecipientVariables>;
export function useListNotificationsByRecipient(dc: DataConnect, vars: ListNotificationsByRecipientVariables, options?: useDataConnectQueryOptions<ListNotificationsByRecipientData>): UseDataConnectQueryResult<ListNotificationsByRecipientData, ListNotificationsByRecipientVariables>;

export function useCountUnreadNotifications(vars: CountUnreadNotificationsVariables, options?: useDataConnectQueryOptions<CountUnreadNotificationsData>): UseDataConnectQueryResult<CountUnreadNotificationsData, CountUnreadNotificationsVariables>;
export function useCountUnreadNotifications(dc: DataConnect, vars: CountUnreadNotificationsVariables, options?: useDataConnectQueryOptions<CountUnreadNotificationsData>): UseDataConnectQueryResult<CountUnreadNotificationsData, CountUnreadNotificationsVariables>;

export function useListChatroomStatsByChatroomIds(vars: ListChatroomStatsByChatroomIdsVariables, options?: useDataConnectQueryOptions<ListChatroomStatsByChatroomIdsData>): UseDataConnectQueryResult<ListChatroomStatsByChatroomIdsData, ListChatroomStatsByChatroomIdsVariables>;
export function useListChatroomStatsByChatroomIds(dc: DataConnect, vars: ListChatroomStatsByChatroomIdsVariables, options?: useDataConnectQueryOptions<ListChatroomStatsByChatroomIdsData>): UseDataConnectQueryResult<ListChatroomStatsByChatroomIdsData, ListChatroomStatsByChatroomIdsVariables>;

export function useFetchPlayroomCreatorToken(vars: FetchPlayroomCreatorTokenVariables, options?: useDataConnectQueryOptions<FetchPlayroomCreatorTokenData>): UseDataConnectQueryResult<FetchPlayroomCreatorTokenData, FetchPlayroomCreatorTokenVariables>;
export function useFetchPlayroomCreatorToken(dc: DataConnect, vars: FetchPlayroomCreatorTokenVariables, options?: useDataConnectQueryOptions<FetchPlayroomCreatorTokenData>): UseDataConnectQueryResult<FetchPlayroomCreatorTokenData, FetchPlayroomCreatorTokenVariables>;

export function useFetchPlayroomInvitedUserToken(vars: FetchPlayroomInvitedUserTokenVariables, options?: useDataConnectQueryOptions<FetchPlayroomInvitedUserTokenData>): UseDataConnectQueryResult<FetchPlayroomInvitedUserTokenData, FetchPlayroomInvitedUserTokenVariables>;
export function useFetchPlayroomInvitedUserToken(dc: DataConnect, vars: FetchPlayroomInvitedUserTokenVariables, options?: useDataConnectQueryOptions<FetchPlayroomInvitedUserTokenData>): UseDataConnectQueryResult<FetchPlayroomInvitedUserTokenData, FetchPlayroomInvitedUserTokenVariables>;

export function useFetchPlayroomParticipantToken(vars: FetchPlayroomParticipantTokenVariables, options?: useDataConnectQueryOptions<FetchPlayroomParticipantTokenData>): UseDataConnectQueryResult<FetchPlayroomParticipantTokenData, FetchPlayroomParticipantTokenVariables>;
export function useFetchPlayroomParticipantToken(dc: DataConnect, vars: FetchPlayroomParticipantTokenVariables, options?: useDataConnectQueryOptions<FetchPlayroomParticipantTokenData>): UseDataConnectQueryResult<FetchPlayroomParticipantTokenData, FetchPlayroomParticipantTokenVariables>;

export function useFetchPlayroomParticipantUserIds(vars: FetchPlayroomParticipantUserIdsVariables, options?: useDataConnectQueryOptions<FetchPlayroomParticipantUserIdsData>): UseDataConnectQueryResult<FetchPlayroomParticipantUserIdsData, FetchPlayroomParticipantUserIdsVariables>;
export function useFetchPlayroomParticipantUserIds(dc: DataConnect, vars: FetchPlayroomParticipantUserIdsVariables, options?: useDataConnectQueryOptions<FetchPlayroomParticipantUserIdsData>): UseDataConnectQueryResult<FetchPlayroomParticipantUserIdsData, FetchPlayroomParticipantUserIdsVariables>;

export function useFetchPlayroomInvitedUserJoinedAt(vars: FetchPlayroomInvitedUserJoinedAtVariables, options?: useDataConnectQueryOptions<FetchPlayroomInvitedUserJoinedAtData>): UseDataConnectQueryResult<FetchPlayroomInvitedUserJoinedAtData, FetchPlayroomInvitedUserJoinedAtVariables>;
export function useFetchPlayroomInvitedUserJoinedAt(dc: DataConnect, vars: FetchPlayroomInvitedUserJoinedAtVariables, options?: useDataConnectQueryOptions<FetchPlayroomInvitedUserJoinedAtData>): UseDataConnectQueryResult<FetchPlayroomInvitedUserJoinedAtData, FetchPlayroomInvitedUserJoinedAtVariables>;

export function useFetchPlayroomCreatorUserHeartbeat(vars: FetchPlayroomCreatorUserHeartbeatVariables, options?: useDataConnectQueryOptions<FetchPlayroomCreatorUserHeartbeatData>): UseDataConnectQueryResult<FetchPlayroomCreatorUserHeartbeatData, FetchPlayroomCreatorUserHeartbeatVariables>;
export function useFetchPlayroomCreatorUserHeartbeat(dc: DataConnect, vars: FetchPlayroomCreatorUserHeartbeatVariables, options?: useDataConnectQueryOptions<FetchPlayroomCreatorUserHeartbeatData>): UseDataConnectQueryResult<FetchPlayroomCreatorUserHeartbeatData, FetchPlayroomCreatorUserHeartbeatVariables>;

export function useFetchPlayroomInvitedUserHeartbeat(vars: FetchPlayroomInvitedUserHeartbeatVariables, options?: useDataConnectQueryOptions<FetchPlayroomInvitedUserHeartbeatData>): UseDataConnectQueryResult<FetchPlayroomInvitedUserHeartbeatData, FetchPlayroomInvitedUserHeartbeatVariables>;
export function useFetchPlayroomInvitedUserHeartbeat(dc: DataConnect, vars: FetchPlayroomInvitedUserHeartbeatVariables, options?: useDataConnectQueryOptions<FetchPlayroomInvitedUserHeartbeatData>): UseDataConnectQueryResult<FetchPlayroomInvitedUserHeartbeatData, FetchPlayroomInvitedUserHeartbeatVariables>;

export function useFetchPlayroomSpectators(vars: FetchPlayroomSpectatorsVariables, options?: useDataConnectQueryOptions<FetchPlayroomSpectatorsData>): UseDataConnectQueryResult<FetchPlayroomSpectatorsData, FetchPlayroomSpectatorsVariables>;
export function useFetchPlayroomSpectators(dc: DataConnect, vars: FetchPlayroomSpectatorsVariables, options?: useDataConnectQueryOptions<FetchPlayroomSpectatorsData>): UseDataConnectQueryResult<FetchPlayroomSpectatorsData, FetchPlayroomSpectatorsVariables>;

export function useFetchPlayroomSpectatorsJoined(vars: FetchPlayroomSpectatorsJoinedVariables, options?: useDataConnectQueryOptions<FetchPlayroomSpectatorsJoinedData>): UseDataConnectQueryResult<FetchPlayroomSpectatorsJoinedData, FetchPlayroomSpectatorsJoinedVariables>;
export function useFetchPlayroomSpectatorsJoined(dc: DataConnect, vars: FetchPlayroomSpectatorsJoinedVariables, options?: useDataConnectQueryOptions<FetchPlayroomSpectatorsJoinedData>): UseDataConnectQueryResult<FetchPlayroomSpectatorsJoinedData, FetchPlayroomSpectatorsJoinedVariables>;

export function useIsUserInPlayroomSpectators(vars: IsUserInPlayroomSpectatorsVariables, options?: useDataConnectQueryOptions<IsUserInPlayroomSpectatorsData>): UseDataConnectQueryResult<IsUserInPlayroomSpectatorsData, IsUserInPlayroomSpectatorsVariables>;
export function useIsUserInPlayroomSpectators(dc: DataConnect, vars: IsUserInPlayroomSpectatorsVariables, options?: useDataConnectQueryOptions<IsUserInPlayroomSpectatorsData>): UseDataConnectQueryResult<IsUserInPlayroomSpectatorsData, IsUserInPlayroomSpectatorsVariables>;

export function useListActivePlayroomSessionsByUserAndGame(vars: ListActivePlayroomSessionsByUserAndGameVariables, options?: useDataConnectQueryOptions<ListActivePlayroomSessionsByUserAndGameData>): UseDataConnectQueryResult<ListActivePlayroomSessionsByUserAndGameData, ListActivePlayroomSessionsByUserAndGameVariables>;
export function useListActivePlayroomSessionsByUserAndGame(dc: DataConnect, vars: ListActivePlayroomSessionsByUserAndGameVariables, options?: useDataConnectQueryOptions<ListActivePlayroomSessionsByUserAndGameData>): UseDataConnectQueryResult<ListActivePlayroomSessionsByUserAndGameData, ListActivePlayroomSessionsByUserAndGameVariables>;

export function useGetPlayroomSessionByPlayroomSessionId(vars: GetPlayroomSessionByPlayroomSessionIdVariables, options?: useDataConnectQueryOptions<GetPlayroomSessionByPlayroomSessionIdData>): UseDataConnectQueryResult<GetPlayroomSessionByPlayroomSessionIdData, GetPlayroomSessionByPlayroomSessionIdVariables>;
export function useGetPlayroomSessionByPlayroomSessionId(dc: DataConnect, vars: GetPlayroomSessionByPlayroomSessionIdVariables, options?: useDataConnectQueryOptions<GetPlayroomSessionByPlayroomSessionIdData>): UseDataConnectQueryResult<GetPlayroomSessionByPlayroomSessionIdData, GetPlayroomSessionByPlayroomSessionIdVariables>;

export function useGetActivePlayroomSessionByPlayroomSessionId(vars: GetActivePlayroomSessionByPlayroomSessionIdVariables, options?: useDataConnectQueryOptions<GetActivePlayroomSessionByPlayroomSessionIdData>): UseDataConnectQueryResult<GetActivePlayroomSessionByPlayroomSessionIdData, GetActivePlayroomSessionByPlayroomSessionIdVariables>;
export function useGetActivePlayroomSessionByPlayroomSessionId(dc: DataConnect, vars: GetActivePlayroomSessionByPlayroomSessionIdVariables, options?: useDataConnectQueryOptions<GetActivePlayroomSessionByPlayroomSessionIdData>): UseDataConnectQueryResult<GetActivePlayroomSessionByPlayroomSessionIdData, GetActivePlayroomSessionByPlayroomSessionIdVariables>;
